/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubTrabalhoRouteImport } from './routes/sub-trabalho'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PalestrasRouteImport } from './routes/palestras'
import { Route as PalestrantesRouteImport } from './routes/palestrantes'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIngressoRouteImport } from './routes/painel.ingresso'
import { Route as PainelHistoricoRouteImport } from './routes/painel.historico'
import { Route as PainelEventoRouteImport } from './routes/painel.evento'
import { Route as PainelDataRouteImport } from './routes/painel.data'

const SubTrabalhoRoute = SubTrabalhoRouteImport.update({
  id: '/sub-trabalho',
  path: '/sub-trabalho',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PalestrasRoute = PalestrasRouteImport.update({
  id: '/palestras',
  path: '/palestras',
  getParentRoute: () => rootRouteImport,
} as any)
const PalestrantesRoute = PalestrantesRouteImport.update({
  id: '/palestrantes',
  path: '/palestrantes',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIngressoRoute = PainelIngressoRouteImport.update({
  id: '/ingresso',
  path: '/ingresso',
  getParentRoute: () => PainelRoute,
} as any)
const PainelHistoricoRoute = PainelHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => PainelRoute,
} as any)
const PainelEventoRoute = PainelEventoRouteImport.update({
  id: '/evento',
  path: '/evento',
  getParentRoute: () => PainelRoute,
} as any)
const PainelDataRoute = PainelDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/palestrantes': typeof PalestrantesRoute
  '/palestras': typeof PalestrasRoute
  '/quem-somos': typeof QuemSomosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/sub-trabalho': typeof SubTrabalhoRoute
  '/painel/data': typeof PainelDataRoute
  '/painel/evento': typeof PainelEventoRoute
  '/painel/historico': typeof PainelHistoricoRoute
  '/painel/ingresso': typeof PainelIngressoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/palestrantes': typeof PalestrantesRoute
  '/palestras': typeof PalestrasRoute
  '/quem-somos': typeof QuemSomosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/sub-trabalho': typeof SubTrabalhoRoute
  '/painel/data': typeof PainelDataRoute
  '/painel/evento': typeof PainelEventoRoute
  '/painel/historico': typeof PainelHistoricoRoute
  '/painel/ingresso': typeof PainelIngressoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/palestrantes': typeof PalestrantesRoute
  '/palestras': typeof PalestrasRoute
  '/quem-somos': typeof QuemSomosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/sub-trabalho': typeof SubTrabalhoRoute
  '/painel/data': typeof PainelDataRoute
  '/painel/evento': typeof PainelEventoRoute
  '/painel/historico': typeof PainelHistoricoRoute
  '/painel/ingresso': typeof PainelIngressoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeria'
    | '/inscricao'
    | '/login'
    | '/painel'
    | '/palestrantes'
    | '/palestras'
    | '/quem-somos'
    | '/recuperar-senha'
    | '/sub-trabalho'
    | '/painel/data'
    | '/painel/evento'
    | '/painel/historico'
    | '/painel/ingresso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeria'
    | '/inscricao'
    | '/login'
    | '/painel'
    | '/palestrantes'
    | '/palestras'
    | '/quem-somos'
    | '/recuperar-senha'
    | '/sub-trabalho'
    | '/painel/data'
    | '/painel/evento'
    | '/painel/historico'
    | '/painel/ingresso'
  id:
    | '__root__'
    | '/'
    | '/galeria'
    | '/inscricao'
    | '/login'
    | '/painel'
    | '/palestrantes'
    | '/palestras'
    | '/quem-somos'
    | '/recuperar-senha'
    | '/sub-trabalho'
    | '/painel/data'
    | '/painel/evento'
    | '/painel/historico'
    | '/painel/ingresso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriaRoute: typeof GaleriaRoute
  InscricaoRoute: typeof InscricaoRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRouteWithChildren
  PalestrantesRoute: typeof PalestrantesRoute
  PalestrasRoute: typeof PalestrasRoute
  QuemSomosRoute: typeof QuemSomosRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  SubTrabalhoRoute: typeof SubTrabalhoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sub-trabalho': {
      id: '/sub-trabalho'
      path: '/sub-trabalho'
      fullPath: '/sub-trabalho'
      preLoaderRoute: typeof SubTrabalhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palestras': {
      id: '/palestras'
      path: '/palestras'
      fullPath: '/palestras'
      preLoaderRoute: typeof PalestrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palestrantes': {
      id: '/palestrantes'
      path: '/palestrantes'
      fullPath: '/palestrantes'
      preLoaderRoute: typeof PalestrantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/ingresso': {
      id: '/painel/ingresso'
      path: '/ingresso'
      fullPath: '/painel/ingresso'
      preLoaderRoute: typeof PainelIngressoRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/historico': {
      id: '/painel/historico'
      path: '/historico'
      fullPath: '/painel/historico'
      preLoaderRoute: typeof PainelHistoricoRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/evento': {
      id: '/painel/evento'
      path: '/evento'
      fullPath: '/painel/evento'
      preLoaderRoute: typeof PainelEventoRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/data': {
      id: '/painel/data'
      path: '/data'
      fullPath: '/painel/data'
      preLoaderRoute: typeof PainelDataRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

interface PainelRouteChildren {
  PainelDataRoute: typeof PainelDataRoute
  PainelEventoRoute: typeof PainelEventoRoute
  PainelHistoricoRoute: typeof PainelHistoricoRoute
  PainelIngressoRoute: typeof PainelIngressoRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelDataRoute: PainelDataRoute,
  PainelEventoRoute: PainelEventoRoute,
  PainelHistoricoRoute: PainelHistoricoRoute,
  PainelIngressoRoute: PainelIngressoRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriaRoute: GaleriaRoute,
  InscricaoRoute: InscricaoRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRouteWithChildren,
  PalestrantesRoute: PalestrantesRoute,
  PalestrasRoute: PalestrasRoute,
  QuemSomosRoute: QuemSomosRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  SubTrabalhoRoute: SubTrabalhoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
